config/routes.rb
Rails.application.routes.draw do
  resources :activities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :source

  validates :uid, :dtstamp, :dtstart, presence: true

  default_scope { newest }
  scope :newest, -> { order :dtstart, :desc }
  scope :future, -> { where "dtstart > ?", Time.now }

  def self.import_event(event, src)
    raise ArgumentError unless event.is_a? Icalendar::Event

    prop_names = event.class.properties
    prop_hash = prop_names.map {|n| [n, event.send(n)]}.to_h
    prop_hash.delete_if {|k, v| v.blank? }
    prop_hash[:source] = src

    act = create! prop_hash
    Rails.logger.info "Imported #{act.uid}"
    act
  end

  def grok
    return @info ||= populate_info
  end

private

  def populate_info
    info = HashWithIndifferentAccess.new

    lines = description.lines.map do |l|
      ls = l.strip
      ls.empty? ? nil : ls
    end
    lines.compact!
    # puts lines.pretty_inspect

    info[:tags] = lines[0].split(',').map do |t|
      t.strip
    end
    info[:tiers] = lines[1]
    info[:author] = lines[2]
    info[:description] = lines[3]
    info[:notes] = lines[4]
    info[:summary] = summary
    info[:location] = location
    info[:start] = dtstart.localtime.rfc2822
    info[:end] = dtend.localtime.rfc2822
    info[:url] = url

    return info
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/source.rb
class Source < ApplicationRecord
  has_many :activities

  validates :name, :uri, presence: true

  scope :active, -> { where active: true }
  scope :outdated, -> { where "strftime('%s', 'now') - strftime('%s', last_refreshed) > frequency" }

  def refresh
    response = VentureBot::GetUriService.new(URI(uri)).call
    self.last_refreshed = Time.now
    Rails.logger.info "Refreshing #{response.base_uri} #{response.status.join}"
    if response.status[0].to_s != '200'
      save
      return false
    end

    data = response
    self.last_modified = response.last_modified
    ical = Icalendar::Calendar.parse data
    events = ical.first.events

    events.collect do |e|
      a = Activity.find_by(uid: e.uid.to_s) or Activity.import_event(e, self)
      a
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.fetch(:activity, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Summary</th>
      <th>Start Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.summary %></td>
        <td><%= activity.dtstart %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @activity.summary %></h3>

<p><%= link_to 'Warhorn page', @activity.url %></p>

<p>Start: <%= @activity.dtstart %></p>
<p>End: <%= @activity.dtend %></p>

<p><%= simple_format @activity.description %></p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VentureBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>